import { NavigationTree } from '@/@types/navigation'
import {
    getDebtPath,
    getDeliveryAddressPath,
    getHomePath,
    getOrdersPath,
    getPaymentsPath,
    getPayoutsPath,
    getReconciliationStatementPath,
    getSalesPath,
} from '@/shared/config'
import { NAV_ITEM_TYPE_ITEM } from '@/shared/config/constants/navigation.constant'

const mainNavigationConfig: NavigationTree[] = [
    {
        key: 'main/products',
        path: getHomePath(),
        title: 'Товары',
        translateKey: 'nav.main.incoming',
        icon: 'documentsIncoming',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'main/orders',
        path: getOrdersPath(),
        title: 'Заказы',
        translateKey: 'nav.main.incoming',
        icon: 'managementsUsers',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'main/sales',
        path: getSalesPath(),
        title: 'Продажи',
        translateKey: 'nav.main.incoming',
        icon: 'documentsDraft',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'main/payments',
        path: getPaymentsPath(),
        title: 'Оплаты',
        translateKey: 'nav.main.incoming',
        icon: 'documentsApproval',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'main/payouts',
        path: getPayoutsPath(),
        title: 'Выплаты',
        translateKey: 'nav.main.incoming',
        icon: 'documentsTasks',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'main/debt',
        path: getDebtPath(),
        title: 'Задолженность',
        translateKey: 'nav.main.incoming',
        icon: 'managementsFolders',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'main/reconciliation-statement',
        path: getReconciliationStatementPath(),
        title: 'АКТ сверка',
        translateKey: 'nav.main.incoming',
        icon: 'managementsContractors',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'main/delivery-address',
        path: getDeliveryAddressPath(),
        title: 'Адрес доставки',
        translateKey: 'nav.main.incoming',
        icon: 'managementsBranches',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
]

export default mainNavigationConfig
