import { NavigationTree } from '@/@types/navigation'
import {
    getDebtPath,
    // getDeliveryAddressPath,
    getMainPath,
    getOrdersPath,
    getPaymentsPath,
    getPayoutsPath,
    getAskActReportPath,
    getRefundsPath,
    getSalesPath,
} from '@/shared/config'
import { NAV_ITEM_TYPE_ITEM } from '@/shared/config/constants/navigation.constant'

const mainNavigationConfig: NavigationTree[] = [
    {
        key: 'home',
        path: getMainPath(),
        title: 'Товары',
        translateKey: 'nav.main.incoming',
        icon: 'mainProducts',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'orders',
        path: getOrdersPath(),
        title: 'Заказы',
        translateKey: 'nav.main.incoming',
        icon: 'mainOrders',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'sales',
        path: getSalesPath(),
        title: 'Продажи',
        translateKey: 'nav.main.incoming',
        icon: 'mainSales',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'refunds',
        path: getRefundsPath(),
        title: 'Возврат',
        translateKey: 'nav.main.incoming',
        icon: 'mainRefunds',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'payments',
        path: getPaymentsPath(),
        title: 'Оплаты',
        translateKey: 'nav.main.incoming',
        icon: 'mainPayments',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'payouts',
        path: getPayoutsPath(),
        title: 'Выплаты',
        translateKey: 'nav.main.incoming',
        icon: 'mainPayouts',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'debts',
        path: getDebtPath(),
        title: 'Задолженность',
        translateKey: 'nav.main.incoming',
        icon: 'mainDebt',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'ask-act-report',
        path: getAskActReportPath(),
        title: 'АКТ сверка',
        translateKey: 'nav.main.incoming',
        icon: 'reconciliationAct',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    // {
    //     key: 'delivery-address',
    //     path: getDeliveryAddressPath(),
    //     title: 'Адрес доставки',
    //     translateKey: 'nav.main.incoming',
    //     icon: 'managementsBranches',
    //     type: NAV_ITEM_TYPE_ITEM,
    //     authority: [],
    //     subMenu: [],
    // },
]

export default mainNavigationConfig
